### PR TITLE
Allow to have numbers not unmarshaled as float

### PR DESCRIPTION
**Pull request by akuracy**

### CODE REVIEW

**Comment by gregdel** [comment]
Hello @akuracy, thanks for you contribution.
I'm not sure changing the default behavior is the right approach. If you have something specific to do while unmarshaling you should probably do it in your own source code.

**Comment by akuracy** [comment]
Hello @gregdel, thank you for your quick reply.

I am using venom with calls to APIv6 which in turn use UnmarshalResponse https://github.com/ovh/venom/blob/master/executors/ovhapi/executor.go#L162
Using results of previous APIv6 calls in venom, i have problems with numbers being put in float, like 42633853 which became 4.2633853e+07

I can patch venom to do unmarshall with UseNumber, it will end up doing 2 unmarshalls

**Comment by gregdel** [comment]
@yesnault what do you think ?

**Comment by marcaudefroy** [comment]
Hi.
Seen with yvonnick. 
Seems the main problem is the risk of compatibility with actual use. 

Not a real problem :

We tag the current version of master (0.1.0 for example).
We merge this PR and we tag it (0.1.1).

If there is an impact, we can still use 0.1.0.

Ok for you? @gregdel

**Comment by gregdel** [comment]
I still don't think this is a good idea. The idea of this API wrapper is to be as thin as possible and to allow developers to rely on its stability.
This pull request doesn't really fulfill this goals.

**Comment by fsamin** [comment]
+1 @marcaudefroy 
(as far i am concerned) `UseNumber` is a standard option of the `encoding/json` package
We definitely should use it to unmarshall the floats the right way

Since the apiWrapper provides `UnmarshalResponse` it should be able to unmarshall the response the right way.

**Comment by rbeuque74** [comment]
Thanks for your contribution, I rebased your pull-request and added a unit-test regarding this modification, to prevent regression.
We will tag this new feature on version 1.1.0, users that don't want it will be able to track version 1.0.0

**Pull request merged**
